#include "./constant.h"
// 所有数值均为国际组单位
double Constant::Distance_per_pixel=1e-3;
double Constant::Time_per_millisecond=1e-3;
double Constant::Origin_charge=3e-10;
double Constant::Origin_mass=1;
double Constant::Test_charge_lower_bound=1e-9;
double Constant::Test_charge_upper_bound=1e-8;
double Constant::Test_mass_lower_bound=1e-3;
double Constant::Test_mass_upper_bound=1e-2;
double Constant::Init_speed_lower_bound=1e-1;
double Constant::Init_speed_upper_bound=3e-1;
double Constant::Init_x_offset_lower_bound=2e-3;
double Constant::Init_x_offset_upper_bound=1e-2;
double Constant::Init_y_offset_lower_bound=-1e-2;
double Constant::Init_y_offset_upper_bound=-4e-3;
double Constant::K=8.988e9;
int Constant::Simulating_load=0x2ff;